databases:
  - name: f.c.clavelina_DB
    databaseName: f.c.clavelina_DB
    user: f.c.clavelina/sophia.university
    region: singapore

services:
  - type: web
    name: f.c.clavelina/sophia.university
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: f.c.clavelina_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false